#kafka配置信息
kafka:
  producer:
    bootstrap-servers: 10.168.1.130:9092                #多个地址以","分隔
    batch-size: 16384                                   #一次最多发送数据量  16K
    retries: 3                                          #发送失败后的重复发送次数
    buffer-memory: 33554432                             #32M批处理缓冲区
    linger: 5                                           #延迟发送时间ms，如果未达到batch-size，但是时间达到linger将发送消息
    username: writer                                    #连接消费用户名
    password: writer-pwd                                #消费连接用户密码
  consumer:
    bootstrap-servers: 10.168.1.130:9092                #多个地址以","分隔
    auto-offset-reset: latest                           #新建消费组时从什么位置开始消费  latest：最近位置   earliest：最早位置
    max-poll-records: 80                                #批量消费一次最大拉取的数据量
    enable-auto-commit: false                           #是否开启自动提交
    auto-commit-interval: 1000                          #自动提交的间隔时间，自动提交开启时生效
    session-timeout: 20000                              #连接超时时间
    max-poll-interval: 15000                            #手动提交设置与poll的心跳数,如果消息队列中没有消息，等待毫秒后，调用poll()方法。如果队列中有消息，立即消费消息，每次消费的消息的多少可以通过max.poll.records配置。
    max-partition-fetch-bytes: 1048576                  #设置拉取数据的大小,1M
    group-id: test-group                                #消费组
    username: reader                                    #连接消费用户名
    password: reader-pwd                                #消费连接用户密码
  listener:
    batch-listener: true                                #是否开启批量消费，true表示批量消费
    concurrencys: 5                                     #设置消费的线程数
    poll-timeout: 1500                                  #只限自动提交
