server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/birkhoff-liu/springboot.git      # 配置Git仓库的地址
          username: birkhoffliu@163.com                                              # Git仓库的账号
          password: lzl130818                                     # Git仓库的密码
