
server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie

user:
  userServiceUrl: http://localhost:8000/

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.birkhoff.cloud.user.feign.UserFeignClient: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应。